### PR TITLE
Introduction of color defines and error behaviour changes

### PR DESCRIPTION
**Pull request by ghost**
Code changes as discussed in the forums.

#tidying up the Code
#Fixing a bug with the alignment of Header and Footer in the main UI ( they were one line to high respectively to low)
#Introduction of color defines: All colors of the UI are now defined and can be changed
#Changes in indicate_error()
You now no longer have to turn of the Odroid Go if an error occurs, it's no possible to Press B to reboot.
Also this option is shown as a Footer on the error display.
#New and better understandable error codes

### CODE REVIEW

**Comment by ghost** [comment]
Heya Crash!

Are you still looking onto this pull request? :D

**Comment by kamotswind** [comment]
> #Changes in indicate_error()

When indicate_error is called the error is fatal and a power cycle is the best course of action. This is due to how the SD card is handled elsewhere in the code.

> #New and better understandable error codes

I think the error changes you made are not going to work out well for people where English is not their primary language. Using contractions should be avoided. You also removed the word "ERROR" from several of the messages which is also not a good idea.

I'd recommend creating two new pull requests. One with the color defines / "tidy up" and a 2nd one with the bug fix. I think the error behavior and message changes are not likely to be accepted.

**Comment by ghost** [comment]
The Odroid GO is still cycled, but you dont have to turn it off and on.
You can just press B for a reset.

Unfortunately crash didnt respond.

**Comment by OtherCrashOverride** [comment]
This PR needs to be broken up into discrete modifications.  I do not see an issue with introducing color defines, however, I do not wish to change the error behavior or error messages at this time.

[edit]
This PR also will not merge against current master.

**Pull request closed without merging**
